name: Linting and Build

on:
  push:
    branches-ignore:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install

      - name: Type check
        run: yarn tsc --noEmit

      - name: Prettier check
        run: yarn prettier --check .

      - name: ESLint check
        run: yarn eslint . --max-warnings=0

      - name: Build
        run: yarn build
